language: ruby
sudo: false

script: bundle exec rake ci

notifications:
  email: false

rvm:
  - 2.3.0

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - jdk_switcher use oraclejdk8